### ISSUE TITLE
This doesn't work.

### ISSUE THREAD

**Issue by charlestephen** [PilarJ/homebridge-github-backup#1]
I'm using a secondary credential as I have MFA turned on and it says it's working but I'm seeing no pushes to Github. Thoughts?

**Comment by kolcun** [comment]
Hi @charlestephen - I've made some slight modifications that let it work with an ssh connection.  There is a little bit more setup to get it going, but working well for me.

**Comment by charlestephen** [comment]
Nice, I changed "main" to "master" for the repo branch to get it to work but this fixed it for me. I should have taken some time to read the code
